//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsdkFaceLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class FsdkSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FsdkSettings defaultInstance = ((FsdkSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FsdkSettings())));
        
        public static FsdkSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int FsdkInternalResizeWidth {
            get {
                return ((int)(this["FsdkInternalResizeWidth"]));
            }
            set {
                this["FsdkInternalResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FsdkFaceDetectionThreshold {
            get {
                return ((int)(this["FsdkFaceDetectionThreshold"]));
            }
            set {
                this["FsdkFaceDetectionThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FsdkHandleArbitraryRot {
            get {
                return ((bool)(this["FsdkHandleArbitraryRot"]));
            }
            set {
                this["FsdkHandleArbitraryRot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FsdkDetermineRotAngle {
            get {
                return ((bool)(this["FsdkDetermineRotAngle"]));
            }
            set {
                this["FsdkDetermineRotAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SkipMinimumFusionScore {
            get {
                return ((int)(this["SkipMinimumFusionScore"]));
            }
            set {
                this["SkipMinimumFusionScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxSkippedFrames {
            get {
                return ((int)(this["MaxSkippedFrames"]));
            }
            set {
                this["MaxSkippedFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PipelineParallelism {
            get {
                return ((int)(this["PipelineParallelism"]));
            }
            set {
                this["PipelineParallelism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PipelineQueueDepth {
            get {
                return ((int)(this["PipelineQueueDepth"]));
            }
            set {
                this["PipelineQueueDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FsdkDetectFeatures {
            get {
                return ((bool)(this["FsdkDetectFeatures"]));
            }
            set {
                this["FsdkDetectFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FsdkDetectFace {
            get {
                return ((bool)(this["FsdkDetectFace"]));
            }
            set {
                this["FsdkDetectFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FsdkDetectExpression {
            get {
                return ((bool)(this["FsdkDetectExpression"]));
            }
            set {
                this["FsdkDetectExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"UJC+Du1VRKrPuVM5zLaKVOxTtraXP+UWc7KXQusqjYYDqoxQGayoxo3dhLAZtT8zVU516R9U39p2XB+eS+D1QuXangk4urbl/5gvbi9IbcedlUkzFQxs0ytqH2nXXZv2RiEAZlKvrUDxI8Xyj8+V2uRpPUJC+Du1VRKrPuVM5zLaKVOxTtraXP+UWc7KXQusqjYYDqoxQGayoxo3dhLAZtT8zVU516R9U39p2XB+eS+D1QuXangk4urbl/5gvbi9IbcedlUkzFQxs0ytqH2nXXZv2RiEAZlKvrUDxI8Xyj8+V2uRpP+kATMhVVo/VQPtT0ew=")]
        public string FsdkActivationKey {
            get {
                return ((string)(this["FsdkActivationKey"]));
            }
            set {
                this["FsdkActivationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.997")]
        public float InstantMatchThreshold {
            get {
                return ((float)(this["InstantMatchThreshold"]));
            }
            set {
                this["InstantMatchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.992")]
        public float NewTemplateThreshold {
            get {
                return ((float)(this["NewTemplateThreshold"]));
            }
            set {
                this["NewTemplateThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.987")]
        public float MatchThreshold {
            get {
                return ((float)(this["MatchThreshold"]));
            }
            set {
                this["MatchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoLearning {
            get {
                return ((bool)(this["EnableAutoLearning"]));
            }
            set {
                this["EnableAutoLearning"] = value;
            }
        }
    }
}
