//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsdkFaceLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class FsdkSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FsdkSettings defaultInstance = ((FsdkSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FsdkSettings())));
        
        public static FsdkSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public float TrackedInstantMatchThreshold {
            get {
                return ((float)(this["TrackedInstantMatchThreshold"]));
            }
            set {
                this["TrackedInstantMatchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.86")]
        public float UntrackedInstantMatchThreshold {
            get {
                return ((float)(this["UntrackedInstantMatchThreshold"]));
            }
            set {
                this["UntrackedInstantMatchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public float TrackedNewTemplateThreshold {
            get {
                return ((float)(this["TrackedNewTemplateThreshold"]));
            }
            set {
                this["TrackedNewTemplateThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.88")]
        public float UntrackedNewTemplateThreshold {
            get {
                return ((float)(this["UntrackedNewTemplateThreshold"]));
            }
            set {
                this["UntrackedNewTemplateThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public float MatchThreshold {
            get {
                return ((float)(this["MatchThreshold"]));
            }
            set {
                this["MatchThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int FsdkInternalResizeWidth {
            get {
                return ((int)(this["FsdkInternalResizeWidth"]));
            }
            set {
                this["FsdkInternalResizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FsdkFaceDetectionThreshold {
            get {
                return ((int)(this["FsdkFaceDetectionThreshold"]));
            }
            set {
                this["FsdkFaceDetectionThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FsdkHandleArbitraryRot {
            get {
                return ((bool)(this["FsdkHandleArbitraryRot"]));
            }
            set {
                this["FsdkHandleArbitraryRot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FsdkDetermineRotAngle {
            get {
                return ((bool)(this["FsdkDetermineRotAngle"]));
            }
            set {
                this["FsdkDetermineRotAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SkipMinimumConfirmations {
            get {
                return ((int)(this["SkipMinimumConfirmations"]));
            }
            set {
                this["SkipMinimumConfirmations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SkipMaxSkips {
            get {
                return ((int)(this["SkipMaxSkips"]));
            }
            set {
                this["SkipMaxSkips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PipelineParallelism {
            get {
                return ((int)(this["PipelineParallelism"]));
            }
            set {
                this["PipelineParallelism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PipelineQueueDepth {
            get {
                return ((int)(this["PipelineQueueDepth"]));
            }
            set {
                this["PipelineQueueDepth"] = value;
            }
        }
    }
}
